'use strict';

const VALID_MOVIE_OBJECT = {
    id: 10,
    title: 'Test movie',
    year: 2022,
    runtime: 100,
    director: 'Piotr P',
    actors: 'actors',
    plot: 'plot',
    posterUrl: 'url',
    generes: ['Comedy', 'Fantasy'],
};

const MOVIES_WITH_TO_LONG_STRINGS = {
    title: {
        id: 10,
        title: Array(256).fill('X').join(),
        year: 2022,
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    director: {
        id: 10,
        title: 'Test movie',
        year: 2022,
        runtime: 100,
        director: Array(256).fill('X').join(),
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
};

const MOVIES_WITH_MISSING_REQUIRED_FIELD = {
    id: {
        title: 'Test movie',
        year: 2022,
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    title: {
        id: 10,
        year: 2022,
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    year: {
        id: 10,
        title: 'Test movie',
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    runtime: {
        id: 10,
        title: 'Test movie',
        year: 2022,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    director: {
        id: 10,
        title: 'Test movie',
        year: 2022,
        runtime: 100,
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
};

const MOVIES_WITH_WRONG_FIELD_TYPE = {
    id: {
        id: 'id',
        title: 'Test movie',
        year: 2022,
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    title: {
        id: 10,
        title: 300,
        year: 2022,
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    year: {
        id: 10,
        title: 'Test movie',
        year: 'year',
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    runtime: {
        id: 10,
        title: 'Test movie',
        year: 2022,
        runtime: 'runtime',
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
    director: {
        id: 10,
        title: 'Test movie',
        year: 2022,
        runtime: 100,
        director: 10,
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Comedy', 'Fantasy'],
    },
};

const MOVIES_WITH_INVALID_GENERES = {
    'empty array': {
        id: 10,
        title: 'Test movie',
        year: 2022,
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: [],
    },
    'nonexisting generes': {
        id: 10,
        title: 'Test movie',
        year: 2022,
        runtime: 100,
        director: 'Piotr P',
        actors: 'actors',
        plot: 'plot',
        posterUrl: 'url',
        generes: ['Invalid genere'],
    },
};

module.exports = {
    VALID_MOVIE_OBJECT,
    MOVIES_WITH_TO_LONG_STRINGS,
    MOVIES_WITH_MISSING_REQUIRED_FIELD,
    MOVIES_WITH_WRONG_FIELD_TYPE,
    MOVIES_WITH_INVALID_GENERES,
};
